host: '127.0.0.1'
port: 9999

width: 1920
height: 1080

max_human: 5
track: True
filter: True
block: True # block visualization or not, True for visualize each frame, False in realtime applications
rotate: False
debug: False
write: False
out: 'none'

body_model:
  module: "easymocap.visualize.skelmodel.SkelModel"
  args:
    body_type: "body25"
    joint_radius: 0.02

camera:
  phi: 0
  theta: -30
  cx: 0.
  cy: 0.
  cz: 6.

scene:
  "easymocap.visualize.o3dwrapper.create_coord":
    camera: [0, 0, 0]
    radius: 1.
    scale: 1.
  "easymocap.visualize.o3dwrapper.create_bbox":
    min_bound: [-3, -3, 0]
    max_bound: [3, 3, 2]
    flip: False
  "easymocap.visualize.o3dwrapper.create_ground":
    center: [0, 0, 0]
    xdir: [1, 0, 0]
    ydir: [0, 1, 0]
    step: 1
    xrange: 3
    yrange: 3
    white: [1., 1., 1.]
    black: [0.,0.,0.]
    two_sides: True

range:
  minr: [-100, -100, -100]
  maxr: [ 100,  100,  100]
  rate_inlier: 0.8
  min_conf: 0.1